-- MySQL Script generated by MySQL Workbench
-- Thu May  7 07:08:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ladadealer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ladadealer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ladadealer` DEFAULT CHARACTER SET utf8 ;
USE `ladadealer` ;

-- -----------------------------------------------------
-- Table `ladadealer`.`Модель`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Модель` (
  `ID модели` INT NOT NULL,
  `Наименование модели` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`ID модели`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Комплектация`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Комплектация` (
  `ID комплектации` INT NOT NULL,
  `ID модели` INT NOT NULL,
  `Наименование комплектации` VARCHAR(128) NOT NULL,
  `Базовая стоимость` INT NOT NULL,
  INDEX `model_idx` (`ID модели` ASC) VISIBLE,
  PRIMARY KEY (`ID комплектации`),
  CONSTRAINT `model`
    FOREIGN KEY (`ID модели`)
    REFERENCES `ladadealer`.`Модель` (`ID модели`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Цвет`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Цвет` (
  `Код цвета` INT NOT NULL,
  `Наименование цвета` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Код цвета`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Цвет модели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Цвет модели` (
  `ID цвет модели` INT NOT NULL AUTO_INCREMENT,
  `Код цвета` INT NOT NULL,
  `ID модели` INT NOT NULL,
  `Директория с изображениями` VARCHAR(128) NOT NULL,
  INDEX `modelcolor_color_idx` (`Код цвета` ASC) VISIBLE,
  INDEX `modelcolor_model_idx` (`ID модели` ASC) VISIBLE,
  PRIMARY KEY (`ID цвет модели`),
  CONSTRAINT `modelcolor_color`
    FOREIGN KEY (`Код цвета`)
    REFERENCES `ladadealer`.`Цвет` (`Код цвета`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `modelcolor_model`
    FOREIGN KEY (`ID модели`)
    REFERENCES `ladadealer`.`Модель` (`ID модели`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Автомобиль в наличии`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Автомобиль в наличии` (
  `ID автомобиля` INT NOT NULL,
  `Актуальная стоимость` INT NOT NULL,
  `ID комплектации` INT NOT NULL,
  `ID цвет модели` INT NOT NULL,
  PRIMARY KEY (`ID автомобиля`),
  INDEX `actual_color_idx` (`ID цвет модели` ASC) VISIBLE,
  INDEX `actual_version_idx` (`ID комплектации` ASC) VISIBLE,
  CONSTRAINT `actual_color`
    FOREIGN KEY (`ID цвет модели`)
    REFERENCES `ladadealer`.`Цвет модели` (`ID цвет модели`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `actual_version`
    FOREIGN KEY (`ID комплектации`)
    REFERENCES `ladadealer`.`Комплектация` (`ID комплектации`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Роль`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Роль` (
  `ID роли` INT NOT NULL,
  `Наименование роли` VARCHAR(64) NOT NULL,
  `Описание роли` TINYTEXT NULL,
  PRIMARY KEY (`ID роли`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Пользователь`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Пользователь` (
  `ID пользователя` INT NOT NULL,
  `Номер телефона` BIGINT NOT NULL,
  `Пароль` VARCHAR(128) NOT NULL,
  `Фамилия` VARCHAR(64) NOT NULL,
  `Имя` VARCHAR(64) NOT NULL,
  `Отчество` VARCHAR(64) NULL,
  `Город` VARCHAR(64) NOT NULL,
  `ID роли` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID пользователя`),
  INDEX `user_role_idx` (`ID роли` ASC) VISIBLE,
  CONSTRAINT `user_role`
    FOREIGN KEY (`ID роли`)
    REFERENCES `ladadealer`.`Роль` (`ID роли`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Личный автомобиль`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Личный автомобиль` (
  `ID ЛТС` INT NOT NULL,
  `ID пользователя` INT NOT NULL,
  `ID модели` INT NOT NULL,
  PRIMARY KEY (`ID ЛТС`),
  INDEX `LTS_user_idx` (`ID пользователя` ASC) VISIBLE,
  INDEX `LTS_model_idx` (`ID модели` ASC) VISIBLE,
  CONSTRAINT `LTS_user`
    FOREIGN KEY (`ID пользователя`)
    REFERENCES `ladadealer`.`Пользователь` (`ID пользователя`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LTS_model`
    FOREIGN KEY (`ID модели`)
    REFERENCES `ladadealer`.`Модель` (`ID модели`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Статус`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Статус` (
  `ID статуса` INT NOT NULL,
  `Наименование статуса` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID статуса`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Запись на сервис`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Запись на сервис` (
  `ID записи` INT NOT NULL,
  `ID ЛТС` INT NOT NULL,
  `ID пользователя` INT NOT NULL,
  `ID статуса` INT NOT NULL DEFAULT 0,
  `Дата заявки` DATE NOT NULL,
  `Описание` MEDIUMTEXT NOT NULL,
  `Дата записи` DATETIME NULL,
  PRIMARY KEY (`ID записи`),
  INDEX `zapis_status_idx` (`ID статуса` ASC) VISIBLE,
  INDEX `zapis_LTS_idx` (`ID ЛТС` ASC) VISIBLE,
  INDEX `zapis_user_idx` (`ID пользователя` ASC) VISIBLE,
  CONSTRAINT `zapis_status`
    FOREIGN KEY (`ID статуса`)
    REFERENCES `ladadealer`.`Статус` (`ID статуса`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zapis_LTS`
    FOREIGN KEY (`ID ЛТС`)
    REFERENCES `ladadealer`.`Личный автомобиль` (`ID ЛТС`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zapis_user`
    FOREIGN KEY (`ID пользователя`)
    REFERENCES `ladadealer`.`Пользователь` (`ID пользователя`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Заявка на автомобиль`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Заявка на автомобиль` (
  `ID заявки` INT NOT NULL,
  `ID автомобиля` INT NOT NULL,
  `Контактный номер телефона` BIGINT NOT NULL,
  `Дата истечения брони` DATE NULL,
  PRIMARY KEY (`ID заявки`),
  INDEX `order_car_idx` (`ID автомобиля` ASC) VISIBLE,
  CONSTRAINT `order_car`
    FOREIGN KEY (`ID автомобиля`)
    REFERENCES `ladadealer`.`Автомобиль в наличии` (`ID автомобиля`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ladadealer`.`Заявка конфигуратор`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ladadealer`.`Заявка конфигуратор` (
  `ID заявки` INT NOT NULL,
  `ID комплектации` INT NOT NULL,
  `ID цвет модели` INT NOT NULL,
  `ID статуса` INT NOT NULL,
  `Контактный номер телефона` BIGINT NOT NULL,
  PRIMARY KEY (`ID заявки`),
  INDEX `conf_version_idx` (`ID комплектации` ASC) VISIBLE,
  INDEX `conf_color_idx` (`ID цвет модели` ASC) VISIBLE,
  INDEX `conf_status_idx` (`ID статуса` ASC) VISIBLE,
  CONSTRAINT `conf_version`
    FOREIGN KEY (`ID комплектации`)
    REFERENCES `ladadealer`.`Комплектация` (`ID комплектации`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conf_color`
    FOREIGN KEY (`ID цвет модели`)
    REFERENCES `ladadealer`.`Цвет модели` (`ID цвет модели`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conf_status`
    FOREIGN KEY (`ID статуса`)
    REFERENCES `ladadealer`.`Статус` (`ID статуса`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
